### ISSUE TITLE
Animação do Painel de controle

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_transcendence#41]
## Done:
- [x] Login switch peg toggling on/off
- [x] control panel shrinking/expanding
- [x] drag effect for login switch
- [x] momentary [toggle switch effect](https://www.youtube.com/watch?app=desktop&v=7ZAn0NLr6KA) for other switches

## Todo:
- [x] Pong logo bouncing to signal loading
- [x] generic function for triggering animations and removing its classes
